const STAT_OPTIONS = [
  'BIOL 243',
  'CHEE 209',
  'COMM 162',
  'ECON 250',
  'GPHY 247',
  'KNPE 251',
  'NURS 323',
  'POLS 385',
  'PSYC 202',
  'SOCY 211',
  'STAM 200',
  'STAT 263',
  'STAT 367'
]

const NSCI_OPTIONS = [
  'NSCI 323',
  'NSCI 324	',
  'NSCI 401	'
]

const COMA_OPTIONS = [
  'BIOM 300',
  'CISC 271',
  'CISC 330',
  'CISC 371',
  'CISC 372',
  'CISC 422',
  'CISC 455',
  'CISC 457',
  'CISC 462',
  'CISC 465',
  'CISC 466',
  'CISC 467',
  'CISC 472',
  'CISC 473',
  'CISC 500',
  'MATH 337',
  'MATH 339',
  'MATH 401',
  'MATH 402',
  'MATH 406',
  'MATH 413',
  'MATH 414',
  'MATH 418',
  'MATH 474',
  'MATH 477',
  'STAT 361',
  'STAT 456',
  'STAT 457',
  'STAT 462',
  'STAT 463',
  'STAT 464',
  'STAT 471',
  'STAT 473',
  'STAT 486'
]

const COIs = [
  // ARTS AND SCIENCE
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/anat/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/anim/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/ansh/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/arab/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/arth/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/ascx/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/astr/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/bchm/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/biom/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/biol/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/badr/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/blck/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/canc/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/crss/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/chem/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/chin/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/clst/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/cogs/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/epid/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/coca/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/comp/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/cisc/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/cwri/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/dram/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/ddht/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/econ/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/empr/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/engl/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/enin/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/ensc/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/film/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/artf/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/fren/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/frst/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/gnds/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/gphy/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/geol/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/grmn/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/devs/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/grek/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/hlth/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/hebr/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/hist/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/indg/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/idis/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/ints/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/inuk/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/itln/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/japn/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/jwst/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/knpe/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/lang/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/llcu/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/latn/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/libs/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/lisc/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/ling/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/math/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/mapp/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/micr/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/mohk/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/musc/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/muth/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/nsci/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/path/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/phar/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/phil/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/phys/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/phgy/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/pols/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/ppec/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/port/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/pact/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/intn/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/psyc/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/qgsp/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/rels/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/repd/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/socy/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/span/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/stat/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/stam/',
  'https://queensu-ca-public.courseleaf.com/arts-science/course-descriptions/writ/',
  // Engineering and Applied Science
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/aspc/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/chee/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/civl/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/cmpe/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/elec/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/ench/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/enph/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/geoe/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/mthe/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/mech/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/mren/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/mine/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/mntc/',
  'https://queensu-ca-public.courseleaf.com/engineering-applied-sciences/courses-instruction/soft/',
  // HEALTH SCIENCES
  'https://queensu-ca-public.courseleaf.com/health-sciences/bhsc/courses-instruction/',
  // NURSING 
  'https://queensu-ca-public.courseleaf.com/nursing/bachelor-nursing-science-course-descriptions/',

  // SMITH
  'https://queensu-ca-public.courseleaf.com/business/bachelor-commerce/courses-of-instruction/by20number/#onezerozeroleveltext/',
  'https://queensu-ca-public.courseleaf.com/business/bachelor-commerce/courses-of-instruction/by20number/#twozerozeroleveltext/',
  'https://queensu-ca-public.courseleaf.com/business/bachelor-commerce/courses-of-instruction/by20number/#threezerozeroleveltext/',
  'https://queensu-ca-public.courseleaf.com/business/bachelor-commerce/courses-of-instruction/by20number/#fourzerozeroleveltext/',
  'https://queensu-ca-public.courseleaf.com/business/bachelor-commerce/courses-of-instruction/by20number/#fivezerozeroleveltext/',

]

export const COMP_PROGRAMS = [
  'https://www.cs.queensu.ca/undergraduate/programs/options/artificial-intelligence.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/options/biomedical-computation.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/options/data-analytics.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/options/security.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/options/game-development.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/options/fundamental-computation.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/specializations/biomedical-computing.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/specializations/cognitive-science.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/specializations/software-design.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/specializations/computing-mathematics-and-analytics.php',
  // 'https://www.cs.queensu.ca/undergraduate/programs/specializations/computing-and-the-creative-arts.php'
]

export { STAT_OPTIONS, NSCI_OPTIONS, COMA_OPTIONS, COIs }